import Activity from './activity.svg';
import Airplay from './airplay.svg';
import AlertCircle from './alert-circle.svg';
import AlertOctagon from './alert-octagon.svg';
import AlertTriangle from './alert-triangle.svg';
import AlignCenter from './align-center.svg';
import AlignJustify from './align-justify.svg';
import AlignLeft from './align-left.svg';
import AlignRight from './align-right.svg';
import Anchor from './anchor.svg';
import Aperture from './aperture.svg';
import Archive from './archive.svg';
import ArrowDownCircle from './arrow-down-circle.svg';
import ArrowDownLeft from './arrow-down-left.svg';
import ArrowDownRight from './arrow-down-right.svg';
import ArrowDown from './arrow-down.svg';
import ArrowLeftCircle from './arrow-left-circle.svg';
import ArrowLeft from './arrow-left.svg';
import ArrowRightCircle from './arrow-right-circle.svg';
import ArrowRight from './arrow-right.svg';
import ArrowUpCircle from './arrow-up-circle.svg';
import ArrowUpLeft from './arrow-up-left.svg';
import ArrowUpRight from './arrow-up-right.svg';
import ArrowUp from './arrow-up.svg';
import AtSign from './at-sign.svg';
import Award from './award.svg';
import BarChart2 from './bar-chart-2.svg';
import BarChart from './bar-chart.svg';
import BatteryCharging from './battery-charging.svg';
import Battery from './battery.svg';
import BellOff from './bell-off.svg';
import Bell from './bell.svg';
import Bluetooth from './bluetooth.svg';
import Bold from './bold.svg';
import BookOpen from './book-open.svg';
import Book from './book.svg';
import Bookmark from './bookmark.svg';
import Box from './box.svg';
import Briefcase from './briefcase.svg';
import Calendar from './calendar.svg';
import CameraOff from './camera-off.svg';
import Camera from './camera.svg';
import Cast from './cast.svg';
import CheckCircle from './check-circle.svg';
import CheckSquare from './check-square.svg';
import Check from './check.svg';
import ChevronDown from './chevron-down.svg';
import ChevronLeft from './chevron-left.svg';
import ChevronRight from './chevron-right.svg';
import ChevronUp from './chevron-up.svg';
import ChevronsDown from './chevrons-down.svg';
import ChevronsLeft from './chevrons-left.svg';
import ChevronsRight from './chevrons-right.svg';
import ChevronsUp from './chevrons-up.svg';
import Chrome from './chrome.svg';
import Circle from './circle.svg';
import Clipboard from './clipboard.svg';
import Clock from './clock.svg';
import CloudDrizzle from './cloud-drizzle.svg';
import CloudLightning from './cloud-lightning.svg';
import CloudOff from './cloud-off.svg';
import CloudRain from './cloud-rain.svg';
import CloudSnow from './cloud-snow.svg';
import Cloud from './cloud.svg';
import Code from './code.svg';
import Codepen from './codepen.svg';
import Codesandbox from './codesandbox.svg';
import Coffee from './coffee.svg';
import Columns from './columns.svg';
import Command from './command.svg';
import Compass from './compass.svg';
import Copy from './copy.svg';
import CornerDownLeft from './corner-down-left.svg';
import CornerDownRight from './corner-down-right.svg';
import CornerLeftDown from './corner-left-down.svg';
import CornerLeftUp from './corner-left-up.svg';
import CornerRightDown from './corner-right-down.svg';
import CornerRightUp from './corner-right-up.svg';
import CornerUpLeft from './corner-up-left.svg';
import CornerUpRight from './corner-up-right.svg';
import Cpu from './cpu.svg';
import CreditCard from './credit-card.svg';
import Crop from './crop.svg';
import Crosshair from './crosshair.svg';
import Database from './database.svg';
import Delete from './delete.svg';
import Disc from './disc.svg';
import DollarSign from './dollar-sign.svg';
import DownloadCloud from './download-cloud.svg';
import Download from './download.svg';
import Droplet from './droplet.svg';
import Edit2 from './edit-2.svg';
import Edit3 from './edit-3.svg';
import Edit from './edit.svg';
import ExternalLink from './external-link.svg';
import EyeOff from './eye-off.svg';
import Eye from './eye.svg';
import Facebook from './facebook.svg';
import FastForward from './fast-forward.svg';
import Feather from './feather.svg';
import Figma from './figma.svg';
import FileMinus from './file-minus.svg';
import FilePlus from './file-plus.svg';
import FileText from './file-text.svg';
import File from './file.svg';
import Film from './film.svg';
import Filter from './filter.svg';
import Flag from './flag.svg';
import FolderMinus from './folder-minus.svg';
import FolderPlus from './folder-plus.svg';
import Folder from './folder.svg';
import Framer from './framer.svg';
import Frown from './frown.svg';
import Gift from './gift.svg';
import GitBranch from './git-branch.svg';
import GitCommit from './git-commit.svg';
import GitMerge from './git-merge.svg';
import GitPullRequest from './git-pull-request.svg';
import Github from './github.svg';
import Gitlab from './gitlab.svg';
import Globe from './globe.svg';
import Grid from './grid.svg';
import HardDrive from './hard-drive.svg';
import Hash from './hash.svg';
import Headphones from './headphones.svg';
import Heart from './heart.svg';
import HelpCircle from './help-circle.svg';
import Hexagon from './hexagon.svg';
import Home from './home.svg';
import Image from './image.svg';
import Inbox from './inbox.svg';
import Info from './info.svg';
import Instagram from './instagram.svg';
import Italic from './italic.svg';
import Key from './key.svg';
import Layers from './layers.svg';
import Layout from './layout.svg';
import LifeBuoy from './life-buoy.svg';
import Link2 from './link-2.svg';
import Link from './link.svg';
import Linkedin from './linkedin.svg';
import List from './list.svg';
import Loader from './loader.svg';
import Lock from './lock.svg';
import LogIn from './log-in.svg';
import LogOut from './log-out.svg';
import Mail from './mail.svg';
import MapPin from './map-pin.svg';
import Map from './map.svg';
import Maximize2 from './maximize-2.svg';
import Maximize from './maximize.svg';
import Meh from './meh.svg';
import Menu1 from './menu1.svg';
import MessageCircle from './message-circle.svg';
import MessageSquare from './message-square.svg';
import MicOff from './mic-off.svg';
import Mic from './mic.svg';
import Minimize2 from './minimize-2.svg';
import Minimize from './minimize.svg';
import MinusCircle from './minus-circle.svg';
import MinusSquare from './minus-square.svg';
import Minus from './minus.svg';
import Monitor from './monitor.svg';
import Moon from './moon.svg';
import MoreHorizontal from './more-horizontal.svg';
import MoreVertical from './more-vertical.svg';
import MousePointer from './mouse-pointer.svg';
import Move from './move.svg';
import Music from './music.svg';
import Navigation2 from './navigation-2.svg';
import Navigation from './navigation.svg';
import Octagon from './octagon.svg';
import Package from './package.svg';
import Paperclip from './paperclip.svg';
import PauseCircle from './pause-circle.svg';
import Pause from './pause.svg';
import PenTool from './pen-tool.svg';
import Percent from './percent.svg';
import PhoneCall from './phone-call.svg';
import PhoneForwarded from './phone-forwarded.svg';
import PhoneIncoming from './phone-incoming.svg';
import PhoneMissed from './phone-missed.svg';
import PhoneOff from './phone-off.svg';
import PhoneOutgoing from './phone-outgoing.svg';
import Phone from './phone.svg';
import PieChart from './pie-chart.svg';
import PlayCircle from './play-circle.svg';
import Play from './play.svg';
import PlusCircle from './plus-circle.svg';
import PlusSquare from './plus-square.svg';
import Plus from './plus.svg';
import Pocket from './pocket.svg';
import Power from './power.svg';
import Printer from './printer.svg';
import Radio from './radio.svg';
import RefreshCcw from './refresh-ccw.svg';
import RefreshCw from './refresh-cw.svg';
import Repeat from './repeat.svg';
import Rewind from './rewind.svg';
import RotateCcw from './rotate-ccw.svg';
import RotateCw from './rotate-cw.svg';
import Rss from './rss.svg';
import Save from './save.svg';
import Scissors from './scissors.svg';
import Search from './search.svg';
import Send from './send.svg';
import Server from './server.svg';
import Settings from './settings.svg';
import Share2 from './share-2.svg';
import Share from './share.svg';
import ShieldOff from './shield-off.svg';
import Shield from './shield.svg';
import ShoppingBag from './shopping-bag.svg';
import ShoppingCart from './shopping-cart.svg';
import Shuffle from './shuffle.svg';
import Sidebar from './sidebar.svg';
import SkipBack from './skip-back.svg';
import SkipForward from './skip-forward.svg';
import Slack from './slack.svg';
import Slash from './slash.svg';
import Sliders from './sliders.svg';
import Smartphone from './smartphone.svg';
import Smile from './smile.svg';
import Speaker from './speaker.svg';
import Square from './square.svg';
import Star from './star.svg';
import StopCircle from './stop-circle.svg';
import Sun from './sun.svg';
import Sunrise from './sunrise.svg';
import Sunset from './sunset.svg';
import Tablet from './tablet.svg';
import Tag from './tag.svg';
import Target from './target.svg';
import Terminal from './terminal.svg';
import Thermometer from './thermometer.svg';
import ThumbsDown from './thumbs-down.svg';
import ThumbsUp from './thumbs-up.svg';
import ToggleLeft from './toggle-left.svg';
import ToggleRight from './toggle-right.svg';
import Tool from './tool.svg';
import Trash2 from './trash-2.svg';
import Trash from './trash.svg';
import Trello from './trello.svg';
import TrendingDown from './trending-down.svg';
import TrendingUp from './trending-up.svg';
import Triangle from './triangle.svg';
import Truck from './truck.svg';
import Tv from './tv.svg';
import Twitch from './twitch.svg';
import Twitter from './twitter.svg';
import Type from './type.svg';
import Umbrella from './umbrella.svg';
import Underline from './underline.svg';
import Unlock from './unlock.svg';
import UploadCloud from './upload-cloud.svg';
import Upload from './upload.svg';
import UserCheck from './user-check.svg';
import UserMinus from './user-minus.svg';
import UserPlus from './user-plus.svg';
import UserX from './user-x.svg';
import User from './user.svg';
import Users from './users.svg';
import VideoOff from './video-off.svg';
import Video from './video.svg';
import Voicemail from './voicemail.svg';
import Volume1 from './volume-1.svg';
import Volume2 from './volume-2.svg';
import VolumeX from './volume-x.svg';
import Volume from './volume.svg';
import Watch from './watch.svg';
import WifiOff from './wifi-off.svg';
import Wifi from './wifi.svg';
import Wind from './wind.svg';
import XCircle from './x-circle.svg';
import XOctagon from './x-octagon.svg';
import XSquare from './x-square.svg';
import X from './x.svg';
import Youtube from './youtube.svg';
import ZapOff from './zap-off.svg';
import Zap from './zap.svg';
import ZoomIn from './zoom-in.svg';
import ZoomOut from './zoom-out.svg';

export const ActivitySvg = Activity;
export const AirplaySvg = Airplay;
export const AlertCircleSvg = AlertCircle;
export const AlertOctagonSvg = AlertOctagon;
export const AlertTriangleSvg = AlertTriangle;
export const AlignCenterSvg = AlignCenter;
export const AlignJustifySvg = AlignJustify;
export const AlignLeftSvg = AlignLeft;
export const AlignRightSvg = AlignRight;
export const AnchorSvg = Anchor;
export const ApertureSvg = Aperture;
export const ArchiveSvg = Archive;
export const ArrowDownCircleSvg = ArrowDownCircle;
export const ArrowDownLeftSvg = ArrowDownLeft;
export const ArrowDownRightSvg = ArrowDownRight;
export const ArrowDownSvg = ArrowDown;
export const ArrowLeftCircleSvg = ArrowLeftCircle;
export const ArrowLeftSvg = ArrowLeft;
export const ArrowRightCircleSvg = ArrowRightCircle;
export const ArrowRightSvg = ArrowRight;
export const ArrowUpCircleSvg = ArrowUpCircle;
export const ArrowUpLeftSvg = ArrowUpLeft;
export const ArrowUpRightSvg = ArrowUpRight;
export const ArrowUpSvg = ArrowUp;
export const AtSignSvg = AtSign;
export const AwardSvg = Award;
export const BarChart2Svg = BarChart2;
export const BarChartSvg = BarChart;
export const BatteryChargingSvg = BatteryCharging;
export const BatterySvg = Battery;
export const BellOffSvg = BellOff;
export const BellSvg = Bell;
export const BluetoothSvg = Bluetooth;
export const BoldSvg = Bold;
export const BookOpenSvg = BookOpen;
export const BookSvg = Book;
export const BookmarkSvg = Bookmark;
export const BoxSvg = Box;
export const BriefcaseSvg = Briefcase;
export const CalendarSvg = Calendar;
export const CameraOffSvg = CameraOff;
export const CameraSvg = Camera;
export const CastSvg = Cast;
export const CheckCircleSvg = CheckCircle;
export const CheckSquareSvg = CheckSquare;
export const CheckSvg = Check;
export const ChevronDownSvg = ChevronDown;
export const ChevronLeftSvg = ChevronLeft;
export const ChevronRightSvg = ChevronRight;
export const ChevronUpSvg = ChevronUp;
export const ChevronsDownSvg = ChevronsDown;
export const ChevronsLeftSvg = ChevronsLeft;
export const ChevronsRightSvg = ChevronsRight;
export const ChevronsUpSvg = ChevronsUp;
export const ChromeSvg = Chrome;
export const CircleSvg = Circle;
export const ClipboardSvg = Clipboard;
export const ClockSvg = Clock;
export const CloudDrizzleSvg = CloudDrizzle;
export const CloudLightningSvg = CloudLightning;
export const CloudOffSvg = CloudOff;
export const CloudRainSvg = CloudRain;
export const CloudSnowSvg = CloudSnow;
export const CloudSvg = Cloud;
export const CodeSvg = Code;
export const CodepenSvg = Codepen;
export const CodesandboxSvg = Codesandbox;
export const CoffeeSvg = Coffee;
export const ColumnsSvg = Columns;
export const CommandSvg = Command;
export const CompassSvg = Compass;
export const CopySvg = Copy;
export const CornerDownLeftSvg = CornerDownLeft;
export const CornerDownRightSvg = CornerDownRight;
export const CornerLeftDownSvg = CornerLeftDown;
export const CornerLeftUpSvg = CornerLeftUp;
export const CornerRightDownSvg = CornerRightDown;
export const CornerRightUpSvg = CornerRightUp;
export const CornerUpLeftSvg = CornerUpLeft;
export const CornerUpRightSvg = CornerUpRight;
export const CpuSvg = Cpu;
export const CreditCardSvg = CreditCard;
export const CropSvg = Crop;
export const CrosshairSvg = Crosshair;
export const DatabaseSvg = Database;
export const DeleteSvg = Delete;
export const DiscSvg = Disc;
export const DollarSignSvg = DollarSign;
export const DownloadCloudSvg = DownloadCloud;
export const DownloadSvg = Download;
export const DropletSvg = Droplet;
export const Edit2Svg = Edit2;
export const Edit3Svg = Edit3;
export const EditSvg = Edit;
export const ExternalLinkSvg = ExternalLink;
export const EyeOffSvg = EyeOff;
export const EyeSvg = Eye;
export const FacebookSvg = Facebook;
export const FastForwardSvg = FastForward;
export const FeatherSvg = Feather;
export const FigmaSvg = Figma;
export const FileMinusSvg = FileMinus;
export const FilePlusSvg = FilePlus;
export const FileTextSvg = FileText;
export const FileSvg = File;
export const FilmSvg = Film;
export const FilterSvg = Filter;
export const FlagSvg = Flag;
export const FolderMinusSvg = FolderMinus;
export const FolderPlusSvg = FolderPlus;
export const FolderSvg = Folder;
export const FramerSvg = Framer;
export const FrownSvg = Frown;
export const GiftSvg = Gift;
export const GitBranchSvg = GitBranch;
export const GitCommitSvg = GitCommit;
export const GitMergeSvg = GitMerge;
export const GitPullRequestSvg = GitPullRequest;
export const GithubSvg = Github;
export const GitlabSvg = Gitlab;
export const GlobeSvg = Globe;
export const GridSvg = Grid;
export const HardDriveSvg = HardDrive;
export const HashSvg = Hash;
export const HeadphonesSvg = Headphones;
export const HeartSvg = Heart;
export const HelpCircleSvg = HelpCircle;
export const HexagonSvg = Hexagon;
export const HomeSvg = Home;
export const ImageSvg = Image;
export const InboxSvg = Inbox;
export const InfoSvg = Info;
export const InstagramSvg = Instagram;
export const ItalicSvg = Italic;
export const KeySvg = Key;
export const LayersSvg = Layers;
export const LayoutSvg = Layout;
export const LifeBuoySvg = LifeBuoy;
export const Link2Svg = Link2;
export const LinkSvg = Link;
export const LinkedinSvg = Linkedin;
export const ListSvg = List;
export const LoaderSvg = Loader;
export const LockSvg = Lock;
export const LogInSvg = LogIn;
export const LogOutSvg = LogOut;
export const MailSvg = Mail;
export const MapPinSvg = MapPin;
export const MapSvg = Map;
export const Maximize2Svg = Maximize2;
export const MaximizeSvg = Maximize;
export const MehSvg = Meh;
export const Menu1Svg = Menu1;
export const MessageCircleSvg = MessageCircle;
export const MessageSquareSvg = MessageSquare;
export const MicOffSvg = MicOff;
export const MicSvg = Mic;
export const Minimize2Svg = Minimize2;
export const MinimizeSvg = Minimize;
export const MinusCircleSvg = MinusCircle;
export const MinusSquareSvg = MinusSquare;
export const MinusSvg = Minus;
export const MonitorSvg = Monitor;
export const MoonSvg = Moon;
export const MoreHorizontalSvg = MoreHorizontal;
export const MoreVerticalSvg = MoreVertical;
export const MousePointerSvg = MousePointer;
export const MoveSvg = Move;
export const MusicSvg = Music;
export const Navigation2Svg = Navigation2;
export const NavigationSvg = Navigation;
export const OctagonSvg = Octagon;
export const PackageSvg = Package;
export const PaperclipSvg = Paperclip;
export const PauseCircleSvg = PauseCircle;
export const PauseSvg = Pause;
export const PenToolSvg = PenTool;
export const PercentSvg = Percent;
export const PhoneCallSvg = PhoneCall;
export const PhoneForwardedSvg = PhoneForwarded;
export const PhoneIncomingSvg = PhoneIncoming;
export const PhoneMissedSvg = PhoneMissed;
export const PhoneOffSvg = PhoneOff;
export const PhoneOutgoingSvg = PhoneOutgoing;
export const PhoneSvg = Phone;
export const PieChartSvg = PieChart;
export const PlayCircleSvg = PlayCircle;
export const PlaySvg = Play;
export const PlusCircleSvg = PlusCircle;
export const PlusSquareSvg = PlusSquare;
export const PlusSvg = Plus;
export const PocketSvg = Pocket;
export const PowerSvg = Power;
export const PrinterSvg = Printer;
export const RadioSvg = Radio;
export const RefreshCcwSvg = RefreshCcw;
export const RefreshCwSvg = RefreshCw;
export const RepeatSvg = Repeat;
export const RewindSvg = Rewind;
export const RotateCcwSvg = RotateCcw;
export const RotateCwSvg = RotateCw;
export const RssSvg = Rss;
export const SaveSvg = Save;
export const ScissorsSvg = Scissors;
export const SearchSvg = Search;
export const SendSvg = Send;
export const ServerSvg = Server;
export const SettingsSvg = Settings;
export const Share2Svg = Share2;
export const ShareSvg = Share;
export const ShieldOffSvg = ShieldOff;
export const ShieldSvg = Shield;
export const ShoppingBagSvg = ShoppingBag;
export const ShoppingCartSvg = ShoppingCart;
export const ShuffleSvg = Shuffle;
export const SidebarSvg = Sidebar;
export const SkipBackSvg = SkipBack;
export const SkipForwardSvg = SkipForward;
export const SlackSvg = Slack;
export const SlashSvg = Slash;
export const SlidersSvg = Sliders;
export const SmartphoneSvg = Smartphone;
export const SmileSvg = Smile;
export const SpeakerSvg = Speaker;
export const SquareSvg = Square;
export const StarSvg = Star;
export const StopCircleSvg = StopCircle;
export const SunSvg = Sun;
export const SunriseSvg = Sunrise;
export const SunsetSvg = Sunset;
export const TabletSvg = Tablet;
export const TagSvg = Tag;
export const TargetSvg = Target;
export const TerminalSvg = Terminal;
export const ThermometerSvg = Thermometer;
export const ThumbsDownSvg = ThumbsDown;
export const ThumbsUpSvg = ThumbsUp;
export const ToggleLeftSvg = ToggleLeft;
export const ToggleRightSvg = ToggleRight;
export const ToolSvg = Tool;
export const Trash2Svg = Trash2;
export const TrashSvg = Trash;
export const TrelloSvg = Trello;
export const TrendingDownSvg = TrendingDown;
export const TrendingUpSvg = TrendingUp;
export const TriangleSvg = Triangle;
export const TruckSvg = Truck;
export const TvSvg = Tv;
export const TwitchSvg = Twitch;
export const TwitterSvg = Twitter;
export const TypeSvg = Type;
export const UmbrellaSvg = Umbrella;
export const UnderlineSvg = Underline;
export const UnlockSvg = Unlock;
export const UploadCloudSvg = UploadCloud;
export const UploadSvg = Upload;
export const UserCheckSvg = UserCheck;
export const UserMinusSvg = UserMinus;
export const UserPlusSvg = UserPlus;
export const UserXSvg = UserX;
export const UserSvg = User;
export const UsersSvg = Users;
export const VideoOffSvg = VideoOff;
export const VideoSvg = Video;
export const VoicemailSvg = Voicemail;
export const Volume1Svg = Volume1;
export const Volume2Svg = Volume2;
export const VolumeXSvg = VolumeX;
export const VolumeSvg = Volume;
export const WatchSvg = Watch;
export const WifiOffSvg = WifiOff;
export const WifiSvg = Wifi;
export const WindSvg = Wind;
export const XCircleSvg = XCircle;
export const XOctagonSvg = XOctagon;
export const XSquareSvg = XSquare;
export const XSvg = X;
export const YoutubeSvg = Youtube;
export const ZapOffSvg = ZapOff;
export const ZapSvg = Zap;
export const ZoomInSvg = ZoomIn;
export const ZoomOutSvg = ZoomOut;